repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        # pre-commit's default_language_version, see
        # https://pre-commit.com/#top_level-default_language_version
        language_version: python3.11
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
#  - repo: https://github.com/asottile/pyupgrade
#    rev: v3.10.1 # Use the sha / tag you want to point at
#    hooks:
#      - id: pyupgrade
#        args: [--py311-plus]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-ast
        language_version: python3.11
      - id: check-yaml
      - id: check-toml
      #- id: fix-encoding-pragma
      - id: end-of-file-fixer
